# Generated by Django 6.0.5 on 2026-07-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('category', models.CharField(help_text="e.g. 'E-commerce · Gadget Store'", max_length=255)),
                ('intro', models.TextField(help_text='Short tagline / description.')),
                ('summary', models.TextField(blank=True, help_text='Longer description for SEO meta.')),
                ('image', models.URLField(blank=True, help_text='Backblaze / S3 URL for project screenshot.')),
                ('url', models.URLField(blank=True, help_text='Live project URL.')),
                ('github', models.URLField(blank=True, help_text='GitHub repo URL.')),
                ('github_api', models.URLField(blank=True, help_text='API repo URL (optional).')),
                ('stack', models.JSONField(default=list, help_text='Tech tags, e.g. ["Next.js","Django REST"]')),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower = appears first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
