# Generated by Django 6.0.5 on 2026-07-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.CharField(blank=True, help_text='Backblaze / S3 URL or relative path (/images/...) for project screenshot.', max_length=500),
        ),
    ]
