# Generated by Django 6.0.6 on 2026-07-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Project screenshot — uploaded to media storage (B2 in production).', null=True, upload_to='projects/'),
        ),
    ]
