# Generated by Django 6.0.5 on 2026-07-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Identifier: 'hero', 'about', 'contact', etc.", max_length=100, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True, help_text='Rich HTML content.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary key-value data, e.g. stats grid.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'site content',
            },
        ),
    ]
