# Generated by Django 6.0.5 on 2026-07-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('content', models.TextField(help_text='Rich HTML — code snippets, images, video embeds.')),
                ('excerpt', models.TextField(blank=True, help_text='Short summary for list pages and SEO.', max_length=500)),
                ('featured_image', models.URLField(blank=True, help_text='Backblaze / S3 URL for the hero image.')),
                ('featured_image_alt', models.CharField(blank=True, max_length=255)),
                ('published_date', models.DateTimeField(db_index=True)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('read_time_minutes', models.PositiveSmallIntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (defaults to title).', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description.', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='blog.tag')),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
