# Generated by Django 6.0.6 on 2026-07-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Hero image — uploaded to media storage (B2 in production).', null=True, upload_to='blog/'),
        ),
    ]
